name: senai_automacao
run-name: ${{ github.actor }} Pipeline Deploy 👍
on: 
  push:
    branches:
      - "develop"
    paths-ignore:
      - "*.txt"
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: INSTALL PACKAGES
        run: |
          sudo apt update -y
          curl https://static.snyk.io/cli/latest/snyk-linux -o snyk
          chmod +x ./snyk
          mv ./snyk /usr/local/bin/
      
      - name: Snyk Auth
        run: |
          snyk -d auth $SNYK_TOKEN
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}

      - name: Add SSH key to agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }} 
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            sudo apt install git -y
            cd /tmp/
            sudo git clone -b develop -n https://github.com/AndersonSR09/-Decathlom-Bikes-.git
            cd -Decathlom-Bikes-
            sudo git checkout HEAD images
            sudo rsync -avhWr /tmp/-Decathlom-Bikes-/images/ /root/efs/
            sudo rm -rf /tmp/-Decathlom-Bikes-
